= Exam Oriented

== 常见废话

* 我想
** I guess
** I think
** I suppose
** I believe
** I suspect
** I image

* 我应该
** I should not forget to
** I need
** I should
** I would like to
** I have to

* 强调的是
** mention
** underline
** emphasize
** highlight
** say
** talk about
** comment on
** remark on
** add（第二三点)

* 的一点是
** the fact that
** the point that
** the matter that
** the one that
** the thing that

* 首先强调
** begin by (mentioning)
** start off by
** start the ball rolling by
** kick off by

* 以一点为开始
** begin with (the fact that)
** start off with
** start the ball rolling with
** kick off with


* 表示说不出来了
** How shall I put it
** What't the word I'm looking for
** How can I explain this


== Part One
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== Basic Question
.例题
[NOTE]
Tell me something about you hometown

* I could start off by saying that ...
* Another point which I'd like to add is that ...
* And also something I guest I shouldn't forget to mention is that ... 



////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== Liking
.例题
[NOTE]
Do you like animals

* Actually, I suppose for the most part I would probably say that I'm quite keen on ... to be more precise I think I have to say that I'm passionate about ...

* I suppose the main reason has something to do with the fact that ...

* As well as that, I'm also a big fan of ... especially ...


////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== Disliking
.例题
[NOTE]
Do you like animals


* I suppose I'm not quite fond of ... and in particular I really can't stand ... I guest that might because of the fact that ...

* On top of that, I'm also not such a fan of things like ... for example ... I suspect the main reason has sth to do with the fact that...


////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== Type of

.例题
[NOTE]
What kind of trasport are there in your city.


* Obviously it goes without saying that there is quite a variety of ...

* Still, I suspect that the most ... could perhaps be ..., And what you have to realize with ... is that

* A second form of ... worth mentioning could be ... , and the main characteristic of ... is that ...

* And of course there is usually things like ...

////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== How/What/When/Where
.例题
[NOTE]
====
* How oftern do you go to the cinema
* Where do you usually buy your clothes.
====

* Well, to be honest, I suppose I should say that it really depends on the exact situation.

* Like for instance, if ... then it's quite possible that I might ...

* Where as in contract, if ... then it's almost certain that I will ... especially



////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== Yes/No
.例题
[NOTE]
Is heath eating important

* Well in actuall fact, if I think about it, I guest in may ways... especially when you consider that...

* Even so, you should also understand that...

* So all in all I guess Imy answer would probablly be both yes and no.


=== Would
.例题
[NOTE]
Would you like to change your name?

If I did something, I would...



////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
== Part Two
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////

== 万能句型
* So, I suppose I should start the ball rolling by talking about  ..., I think the one I would like to pick is ...

* Now concerning with the matter of ..., the thing that need to be highlighted here is that...


* Moving forward to the issue of ..., I guess I should underline the fact that ...


* The cut a long story short, as my very last point, with reference to the question of ...


////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== People
.例题 
[NOTE]
Descript a person that have influenced you

* Well, if i think about it , there are actually a number of of person that ...  in the past few decades/years/months that worth mentioning.

* Though, due to the restriction of time, I guess I would like to talk about the one that I am  *conversant* with the most.

* I suppose I should start the ball rolling by firstly talking about ...

* ...

* In my experience, he might be one of  the most wondful/talented/happy/geneous/generous person that I'v ever known.

* For one thing ...

* Besides that, I guess I should not forget to highlight that fact that ...

* And also, I think I would like to add that ...


////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
=== Experience
.例题 
[NOTE]
Descript a surprise you have

* Well, if i think about it , there are actually a number of of ... that I'v ever had in the past few decades of my life that worth mentioning.

* Though, due to the restriction of time, I guess I would like to talk about the time that ... a few months/years ago.

* If I don't remember it wrong, about serveal weeks before then, ... I was ... 或者 While most of others is ..., I instead decided to ...

* You can imagine (the big smile on my face) 或者 how sad/depressed/miserable/nervous/excited/thrilled/delighted/astonished/content I was when see/witness/expreience/received/finished/accomplished ...

* I suppose 对应第四句(How you Feel, why you think so)