== tv program / news / story

* Well to be honest, I havn't pay much attention to tv programs recently, so I can't think of a very intersesting one to tell. However, even though what I am going to tell  maight be a little trival, it do left deep impression for me.

* I guess I should probably start the ball rolling by talking about what it is, and it's basically a little news story about a young person who was praised by the local goverment for he had helped a old lady to get up after he found that the lady was lying in the center of a street.

* One maight wonder that how could such a trivil story managed to be reported on the tv news program and even get the attention of the goverment, but the thing I have to remind you is that actually there has been some trust crisis in China between the young generation and the old generation. To be more precise, the youth maight usually hesitate to lend their helping hand to the elderly who seems to be in urgent need of help, for they are truely afraid of being accused that they are the cause of the injury, and therefore should be responsible for the medical fee that maigh happen afterwards.

* I believe that this news is of significant influcence to the society. 

* For one thing, it's like the sivler lining in the could that shows us that there are still a lot of kind-hearted people who are willing to help others and are not afraid of misunderstandings that maight happen.

* Besides that, it also encourghs people that the good things we do would finally appreciated by others and even the whole socity.


* I guess after the news was reported, more and more people would start to help others again.


== handcraft / present

* Well to be honest,I suppose there are a number of interesting handcrafts that is worthing mentioning here, but due to the restriction of time, I would like to talk about the one that have some special meaning for me.

* I guess I should start the ball rolling by talking about what it is, and it's baically a glass statues that I designed for my wife as her birthday presents a few years ago. The main body of the gift are two cute pigs kissing each other, and in the right bottom there are a sentence that says: to my be only loved girl.

* The presence is of significant importance to me and to my wife I guess.

* I suppose the thing you have to understand is that, my wife was born in a single parent family which gives her plenty of good qualities such as diligent, caring, compassonate etc. But at the same time she was also some times insecure deep in her heart about relationships especially marriage. To be more precise, when we first fell in love with each other, I believe she used to be worry about her irreplaceability to me as a wife.

* By sending her this present and emphasizing to her how unique she is to me, I gradually opened her heart and convicenced her that there is nothing to worry about. 

* Today, after several years of living togher, we have been married for 4 years and had a very lovely baby 8 months ago. I always thank god for he had help me find my love and soul mate.


== building / historic place 
* Well if i think about it, there are acually a number of interesting buildings/historic places that I'm farmiliar with which I guess are worth mentioning here. But due to the restriction of time, I suppose I should pick the one that is most impressive for me.

* I guess I should start the ball rolling by talking about what it is, and it's actually Leifeng Pagoda, one of the most renowed temple in Hanzhou even in China. And also it is among top ten tourist attractions around West Lake, which is the landmark of Hanzhou. 

* I image that this pagoda is famous for serval reasons.

* For thing, it is associated with a touching loving story between a white snake and a mortal man. Legend has it that a white snake named Bai suzhen took on the appearance of beautiful a lady met a   scholar named Xu Xiang on a rainy day. And they fell in love with each other *at first sight* and soon get marriage. But bai suzhen was later imprisoned by Monk Fahai in Leifeng pagoda in order to end this unusual relationship. Of cause finally there was a happy ending.  

* Another more essential factor contributing to it's famouseness is that, it's actually a truely ancient building that can trace back to the wuyue era thousands of years ago. So this temple is of significant historic importances and is a cultural heritage to all Chinese people even the whole world.
