== A TV program / news / story

* Well to be honest, I haven't pay much attention to TV programs recently, so I can't think of a very interesting one to tell. However, even though what I am going to tell might be a little trivial, it does left deep impression for me.

* I guess I should probably start the ball rolling by talking about what it is, and it's basically a little news story about a young person who was praised by the local government for he had helped a old lady to get up after he found that the lady was lying in the center of a street.

* One might wonder that how could such a trivial story managed to be reported on the tv news program and even get the attention of the government, but the thing I have to remind you is that actually there has been some trust crisis in China between the young generation and the old generation. To be more precise, the youth might usually hesitate to lend their helping hand to the elderly who seems to be in urgent need of help, for they are truly afraid of being accused that they are the cause of the injury, and therefore should be responsible for the medical fee that might happen afterwards.

* I believe that this news is of significant influence to the society. 

* For one thing, it's like the silver lining in the cloud that shows us that there are still a lot of kind-hearted people who are willing to help others and are not afraid of misunderstandings that might happen.

* Besides that, it also encourages people that the good things we do would finally appreciated by others and even the whole society.


* I guess after the news was reported, more and more people would start to help others again.


== A handcraft / present

* Well to be honest, I suppose there are a number of interesting handcrafts that is worth mentioning here, but due to the restriction of time, I would like to talk about the one that have some special meaning for me.

* I guess I should start the ball rolling by talking about what it is, and it's basically a glass statue that I designed for my wife as her birthday presents a few years ago. The main body of the gift is two cute pigs kissing each other, and in the right bottom there is a sentence that says: to my only beloved girl.

* The presence is of significant importance to me and to my wife I guess.

* I suppose the thing you have to understand is that, my wife was born in a single parent family which gives her plenty of good qualities such as diligent, caring, compassionate etc. But at the same time she was also sometimes insecure deep in her heart about relationships especially marriage. To be more precise, when we first fell in love with each other, I believe she used to be worry about her irreplaceability to me as a wife.

* By sending her this present and emphasizing to her how unique she is to me, I gradually opened her heart and convinced her that there is nothing to worry about. 

* Today, after several years of living together, we have been married for 4 years and had a very lovely baby 8 months ago. I always thank god for he had help me find my love and soul mate.


== A building / historic place 
* Well if i think about it, there are actually a number of interesting buildings/historic places that I'm familiar with which I guess are worth mentioning here. But due to the restriction of time, I suppose I should pick the one that is most impressive for me.

* I guess I should start the ball rolling by talking about what it is, and it's actually Leifeng Pagoda, one of the most renowned temple in Hangzhou even in China. And also it is among top ten tourist attractions around West Lake, which is the landmark of Hangzhou. 

* I image that this pagoda is famous for several reasons.

* For thing, it is associated with a touching loving story between a white snake and a mortal man. Legend has it that a white snake named Bai suzhen took on the appearance of beautiful a lady met a   scholar named Xu Xiang on a rainy day. And they fell in love with each other *at first sight* and soon get marriage. But Bai suzhen was later imprisoned by evil Monk Fahai in Leifeng pagoda in order to end this unusual relationship. Of cause finally there was a happy ending.  

* Another more essential factor contributing to its famousness is that, it's actually a truly ancient building that can trace back to the Wuyue era thousands of years ago. So this temple is of significant historic importance and is a cultural heritage to all Chinese people even the whole world.


== A experience you in which you helped others
* Well, to be honest, there are a number of experiences that I helped others, because I usually consider myself as a kind hearted gay. But due to the restriction of time, I guess I should talk about the one that I remember most clearly.

* I suppose I should start the ball rolling by talking about when did it happen, and it actually happened more 10 years ago when I was still a student in the Zhejiang University, which is one of the most renowned universities in China.

* The other day, I was riding a bicycle on my way back to my campus, when all of a sudden two strangers, who seemed to be a couple, gently stopped me, and asked if I could lend them some money. They said that they were doing some business in this city during which they lost all belongs and the money in them.

* While there had been a lot of frauds that were reported on the mass media these days, which would probably made most of people to think that these two strangers were also some sort of cheaters whose only purpose was to cheat me out of some money, I instead lent them some money without a second thought.

* Because I believe that even though there are liars, there are also some people who truly need some help from us. If we stand there watching all the time, one day we may find that we are in a situation in which we are the person who need some support from others, while sadly there is no one who is willing to help us.

== An experience you in which others helped you
* Well, to be honest, I was given assistant by others for a plenty of times most of which I guess is worth mentioning here. But due to the restriction of time, I guess I should talk about the one that I remember the most clearly.

* I suppose I should start the ball rolling by talking about when did it happen, and it actually happened several years ago when I was traveling in a foreign city named Suzhou, one of the most renowned city in China.

* At the last day of my traveling, I sadly found that I have lost my wallet and all money in it. Just when I was wandering in a street thinking about what to do next, I saw a young man riding a bicycle towards me who seemed like a student. I intended to take a chance to stop him and ask him if he could lend me some money. After telling him my story, I was surprised to find that he trusted me and offered help generously.

* While there had been a lot of frauds that were reported on the mass media these days, which would probably make most of people to think that I was also some sort of cheater whose only purpose was to cheat some money, the young man instead lent me the money without a second thought.

* He did the right thing, i believe. I also believe that even though there are liars, there are also some people who truly need some help from us. If we stand there watching all the time, one day we may find that we are in a situation in which we are the person who need some support from others, while sadly there is no one who is willing to help us.


== A book / novel / story
* Well, to be honest, I'm quite fond of reading books/novel/stories, and there are a number of interesting ones that I guess are worth mentioning here. But due to the restriction of time, I guess I should pick the one that impressed me the most.

* I suppose I should start the ball rolling by talking about what it is, and it's actually a novel serials named __Tome Robber's Journals__, which were recommended by one of my colleague a few months ago when we were having a trip on a island of Thailand. 

* It's basically a book serial about a young man named Wuxie, our main character, who's hailing from an ancient family that had been tomb riders for centuries.

* As the story goes, mysteries that had been covered for thousands of years were slowly revealed. And more importantly, the main character Wuxia gradually realized that the people around him were not who they seem to, and he could trust no one in this tomb robbing world full of deceits and lies even his best friend and family.

* This novel is quite prevalent among young people especially young women. I guess the main reason have a lot to do with the fact that the stories in it is not only attractive and fancy, but also the author did a fantastic job of portraying characters in it vividly. What else is that after reading the book, one would usually try to reflect on their life and re-access the priorities in it.

== A happy family event
* Well, if I think about it, there are actually numerous happy moments in my family that I guess are all worth mentioning here. But due to the restriction of time, i suppose I should pick the one that is most impressive to me.

* I image I should start the ball rolling by talking about what the event was, and it was actually as simple as my whole family went out and buy stuffs for the Traditional Chinese spring festival together very long time ago when I was still a little kid who is about 7 years old. 

* If I don't remember it wrong, I few days before then, my parents had been busy cleaning the house and preparing food in case some guest might visit us on these special days of a year. One day they suddenly decided that they should go to the market in the center of the city to shop for something that were still missing, and they asked my brothers and I whether or not we would like to go together.

* It goes without saying that we agreed to go without a second thought, since my brothers and I had never being the market before, and were very curious about it.

* For me, however, it's not only just the first time I went to the city, but one of the happiest memories I have ever had. The thing I guess I would have to underline here is that, it is one of a few times my whole family do some relaxing thing together, which even today I can still remember vividly.

* And besides that, it was also my first time to have the right and opportunity to decide what food to buy. And obviously I recommended my parents to buy more candies.

== A house you want to live in
* Well to be honest, I have been dreaming about living in a fancy house for years, and I'm truly glad to have this opportunity to talk it here.

* I guess I should start the ball rolling by talking about where this place is, and it's actually a house at the foot of the Laohe Mountain which is a small yet well-known mountain near the Yuquan campus of Zhejiang University in Hangzhou.

* There are plenty of benefits I guess I can get by live in such a place. 

* For one thing, it's fairly spacious and could contain a lot of rooms. So I guess I can have my own reading room where I can read books or coding. What's more attractive is the big multifunctional living room, in which my whole family can watch TV or play indoor games together.

* Another very important factor I guess I shouldn't forget to mention is the confortable and big back yard it has. Not only can we plant trees or flowers there, but more importantly, my little boy who is only about 1 year old can really have some happy childhood there.

* And last but not least, is it's enjoying surroundings and amenities. In fact I have been planning to take a regular jog every morning to keep myself fit, but the plan is continuously aborted due the lack of clean places that I can have easy access to.

== A recent happy event
* Well I'm really proud to say that I have never been happier then recently, since the birth of my little baby boy who is now about 1 year old. And I'm quite joyful to have this opportunity to talk about one of the good moments I had with my boy.

* I guess I should start the ball rolling by talking about what this event is, and it's actually as simple as my whole family taking my little angle out to have some fresh air in a public park named Xixi wet land which is one of newest and also most renowned tourist attractions in Hangzhou. It happened on a sunny weekend a few months ago, which my wife and I considered as quite suitable for the outings of kids.

* If I don't remember it wrong, that day all members of my family who is living in Hangzhou went out together, because they are all fairly excited about playing with this naughty boy.

* I suppose I have to say that it might be one of the happiest moments I have ever had. 

* For one thing, laugh and happiness can really be infectious especially when it comes from a kid. In fact, I remember that my wife and I had laughed to tears several times by some hilarious actions performed by our son at that day.

* And besides that, I guess one thing you might not know is that my boy had been allergy to several materials in daily life such as alcohol and potatoes, and we were truly worried that he might be allergy to pollen as well which is awful since he might be deprived of enjoying the most beautiful season in a year that is spring. You can image the big smile on my face and how ecstatic I was when I found that he is totally ok with pollen or anything that might exist in the air of the park that day.

== A goal you want to achieve
* Well If I think about it, there are a number of goals that I wish to achieve in the future, but due to the restriction of time, I guess I would like to pick the most exciting one for me.

* I suppose I should start the ball rolling by talking about what the goal is, and it's actually about buying a new house in Hangzhou, to be more precise buy a house at the foot of the Laohe Mountain near the Zhejiang University, which is one of the most renowned universities in China.

* I guess I need to make much more money than now in order to able to afford such a house, since it might cost a fortune to buy a house in major cities of China, especially a habitable one like Hangzhou. So guess I have a long way to go before I can achieve that goal, may be at least 10 years.

* There are plenty of benefits I guess I can get by live in such a place. 
...

== A person who like to travel by plane
* Well If I think about it, a lot of my friends are quite fond of traveling by plane, most of whom might be worth mentioning here. But due to the restriction of time, I suppose I should pick the one that I'm conversant with the most.

* I guess I should start the ball rolling by talking about who this person is, and her name is Claire, who is a former colleague of mine, when I was still working for my first company after I graduated from university.

* Generally the places she would like to travel involves some natural tourist attraction as well as some great cities such as London. 

* I image there might be a number of reasons about why she is such a big fan of traveling by plane.

* For one thing, as I known, she is fairly passionate about taking trips, especially to foreign countries. Not only is taking a plane quite a very efficient way of traveling, sometimes it's actually the only way. For example, the only feasible way for a Chinese tourist to get to Philippines is probably flying, for there is the pacific ocean between those two countries and there is seldom a *Cruise Line* between these two places.

* Another thing I suppose I shouldn't forget to mention is that she is also a hard worker who is willing to do anything to be excellent in her job. And since she is working for an international corporation, who has multiple sites around the world, she has to travel a lot between these sites. However, it's not that she is forced take travels like most other people do, but she truly enjoyed it for she actually sees it as an opportunity to build her *internationally vision* and *enlarge her horizon*.


.坐飞机
* take a  plane/airplane
* go by  plane/air/airplane
* travel by plane/air/airplane
* flying


== a special festival in your culture
* Well, if I think about it, in Chinese culture there are actually a number of important festivals that are worth mentioning here, such as the Middle autumn festival, the Qingming festival and the Dragon Boat Festival. But due to the restriction of time, I guess i should pick the one that is most significant for most Chinese people.

* I guess I should start the ball rolling by talking about what this festival is, and it's actually the Spring festival, which happens at the start of the Chinese new year.

* When that festival is about to come, families usually would clean their houses thoroughly in the wish of putting away old things, which in our language is called "sweeping the dust". 

* Another important activity is shopping, which also usually happens before that festival. You might know that Chinese people are generally thrifty, but they become quite generous in their spending during these days. For example, they would buy everyone in their family new clothes, whether they need them or not. So Chinese New Year, like Christmas in western countries, is a shopping boom time.

* I believe I have to sad this festival is the most important one for most Chinese people.

* For one thing, it is one of a few chances for some family whose members are working outside their hometown to reunion. In fact, the Chinese New year’s eve feast is a "must do" dinner with of family members reuniting. Chinese will try hard to make this family event, often traveling long distances even from foreign countries. This is actually the main reason for huge travel stress throughout China.

* As well as that, it ...


== a short vocation

