== Writing 1
.题目
[NOTE]
====
给定问题和一个别人的解决思路，问是问是不是同意该解决方法
To what extent do you agree or disagree
====

=== 第一段 给出错误方法，批判之

引出别人的解决问题的思路  ... have reached such proportions that people feel  ... (sth must be done) to resolve these problems.

说别人观点是错的，并给出简单原因 Whether this will resolve the problem is very unlikely as ...

继续解释为什么别人是错的 That is, if ... then ...

让步，说这个解决方法有一定的好处 Nevertheless, ...

转折，说虽然我承认这个解决方法目标是好的，但是并不认为他能解决问题 Howerver, although I respect the aims of ... to resolve the issue of and support their cause, I do not believe it is the best or only way to ... 

=== 第二段 给出抽象方法
引出所有类似问题的根源 All ... problems, whether it is ... or ..., arise from ...

然后给出一个抽象解决方法，比如集体意识或公德心 Therefore, the solution to all these problems is ...

阐述这个抽象方法 What is meant by this is that ...

解释抽象为啥为啥有效，即当这个前提存在时，会咋样  After all, if ... 

=== 第三段 给出具体方法从而达到抽象方法

给出具体解决方法 What is needed, therefore, is ...
 
说明这个具体的解决方法是所有问题的钥匙 ... is the key to all problems and it start from ... all the way to ... and ... 

给出这个具体方法需要做A，需要做B  Futhermore, ... means that ... ... means that

=== 第四段 总结说明我们可行
阐述我们虽然听起来不合实际，但是其实很合实际。This may sound like utopia, but it is not: if .... then ... 

虽然是一个长期的解决方法，但是是可行的解决方法 These are perhaps long term solutions, but they are more realistic solutions than ...




///////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////

== Writing 2
.题目
[NOTE]
====
给定一个趋势，问这个趋势的好处比缺点好多少
To what extent do the advantages outweigh the disadvantage?
====

=== 第一段 附会，给具体论点

马上给出论点，然后细化论点说对趋势对日常生活有啥影响 ... certainly has the potential to bring about great advances for humankind. On a daily basis, we are eyewitnesses to how ...

=== 第二段 说那些地方和人能享受该趋势的好处

说在哪些地方哪些方面我们可以看到这个趋势 In ...(some place) we can observe a growing ... trend in那些地方 ... (some aspect) 

给具体例子 

将例子抽象化 In particular, ...

=== 第三段 说有些地方和人不能享受好处
说好处并没有在所有地方被享受 However, it is not presently guaranteed that these advances are equally shared by all members of the global community.

The truth lies somewhere closer to the fact that ... often have negative effects on ...

=== 说该趋势的问题
说一些缺点，然后应对措施 Many argue that the cost of ... are too high and that ... (sth must be done)  before ...

=== 总结，需要给负面影响更多关注，
因此需要给负面影响更多的关注 Therefore, it is necessary for the  ... to place greater emphasis on the impact of ... on human welfare. 

如何消除负面影响 和 In order to achieve a just and equal distribution of the benefits of ..., its negative side effects need to be counteracted by reforms in ... at international, reigional, and local levels.

只有这么做才有什么好处 Only by further developing the way in which ... can we make sure that ...